### ISSUE TITLE
Git-Diff doesn't work for projects opened by Project Viewer

### ISSUE THREAD

**Issue by bladeski** [jccguimaraes/atom-project-viewer#20]
Default Git-Diff functionality does not work for projects opened from the Project Viewer sidebar.
Project opened from Project Viewer:
![image](https://cloud.githubusercontent.com/assets/7465289/12292145/367263e2-b9e3-11e5-8f5b-43af6e1b6340.png)
Same project opened by "Add Project Folder..." in "File" menu:
![image](https://cloud.githubusercontent.com/assets/7465289/12292162/4b5df8ac-b9e3-11e5-8474-ebc094f5f15d.png)

**Comment by jccguimaraes** [comment]
thanks for reporting this.
will have a look at the why that is happening

**Comment by jccguimaraes** [comment]
hi @bladeski.
did some investigating and found that git-diff only shows diffs in the gutter of the project, not actually in the tree-view cenario.

I don't have those issues and i am having a hard time replicating it.
Can you give me more feedback?
Also, on first image you have one project and on the second you have 2 projects.

Thanks

**Comment by olimpux** [comment]
is not git-diff, it means that the color of the files in the tree-view are not showing, this is happening to me also, when i open a project from project viewer those colors are not appearing, and i don't know wich files have uncommited changes

**Comment by jccguimaraes** [comment]
did you guys have always this? could it be something regarding the new versions of Atom that implemented some changes...
i need more investigation.

**Comment by bladeski** [comment]
I've only recently started using Atom, and this only occurred yesterday after installing the Project Viewer plugin. Also it only occurs with projects opened with the plugin - other projects are fine. Also, on the second image I sent one project is opened with Project Viewer, the other by manually opening a project folder. When I do this it fixes the problem for both projects, but defeats the purpose of using the  plugin. So to summarise...
1. Add project to blank workspace from File menu - works fine
2. Add project to blank workspace from Project Viewer - colour highlighting on files missing
3. Add project to (2.) from File menu - fixes colour highlighting for both projects

I have removed and reinstalled the plugin, but with no improvement.

**Comment by jccguimaraes** [comment]
ok. thanks for sending more intel.
This is really weird as I don't have this issues, and clearly is something from PV.
Are you on Win, OSX or Linux?

**Comment by bladeski** [comment]
I am on Windows, using Atom 1.3.3

**Comment by jccguimaraes** [comment]
I am on an OSX so that can probably be the reason. I can only test in a few days on a windows as i am way these days. Sorry

**Comment by bladeski** [comment]
No problem. Thanks.

**Comment by olimpux** [comment]
i am also on Windows, so maybe is some lib missing, i will test it on Linux

**Comment by jccguimaraes** [comment]
this seems to be something with Atom in Windows. Been experimenting the commands to open a folder and it seems not to be from the package itself.
will investigate more.

**Comment by bladeski** [comment]
That is odd as it only seems to happen when the Project-Viewer plugin is enabled

**Comment by jccguimaraes** [comment]
Yeah, been digging more and more and I really don't see the why, but it seems from the plugin as you said.

It only uses `atom.project.addPath` and `atom.project.removePath` and it seems that this is what the Add Project Folder does at it's core after opening the `pickFolder` method.

Need more testing. Sorry about the delay

**Comment by bladeski** [comment]
No problem. Though I must say, having used the plugin for a few weeks now,
I think it is one of the most useful plugins for Atom I have found! Thanks
for the work you've put into it!

**Comment by jccguimaraes** [comment]
thanks @bladeski. Really happy you're finding it useful! :)
will continue to improve and if you have features just shoot.
Meanwhile will try to see what is the problem here.

**Comment by jasesmith** [comment]
Hope this helps... I am experiencing the same issue with git-diff treatments on the file tree and open file tabs. I've noticed that when I open a project with the Project Viewer, the files don't recognize their git status until I open one of the files. Then, when the Atom window is not the active window, the files lose their git status treatment again until I interact with the file. Here's a screenshot of an Atom window with a project opened directly (not using the Project Viewer) and another window with the same files open (using the Project Viewer) after the window has been inactive and then active again (files lost their git status treatment). You can see the file contents in the editor pane have indicators on the lines changed, but no indicators at the file tree or file tab levels.

![project-viewer-git-issue](https://cloud.githubusercontent.com/assets/1619521/13013779/38c8703a-d16e-11e5-8ba1-47d7046a07fc.png)

FYI: The Project Viewer is so great otherwise! It has become a permanent fixture in my Atom Environment.

**Comment by jccguimaraes** [comment]
Hi @jasesmith.
Thanks for adding more input!
Thought this was a windows issue but guess your having it on an osx machine :(
Can't figure it out yet :( sorry

Thanks for letting me know this package is a must :D

**Comment by jccguimaraes** [comment]
hey @bladeski and @olimpux found this issue closed on Atom https://github.com/atom/atom/issues/10757 that seems to be related.
If you updated your Atom, can you tell me if this continues to happen?
Thanks

**Comment by bladeski** [comment]
Unfortunately not - I'm using 1.5.3 and still having the same problem, but
only when using Project Viewer... it really is bizarre!

**Comment by jccguimaraes** [comment]
i have implemented a new aproach on the refactor and hope it will address this issue, unfortunattly it is still a long way until I finish the new version... can't manage to get the time for it :(

**Comment by bladeski** [comment]
No problem. I look forward to it, but still see the plugin are being good
enough not to get rid of it in the meantime. Thanks.
